apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
      version: v1
  template:
    metadata:
      labels:
        app: spring-server
        version: v1
    spec:
      containers:
      - name: spring-server
        image: spring-server:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_VERSION
          value: "v1"
        - name: ZOOKEEPER_ENABLED
          value: "false"
      imagePullSecrets:
        - name: default-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
      version: v2
  template:
    metadata:
      labels:
        app: spring-server
        version: v2
    spec:
      containers:
        - name: spring-server
          image: spring-server:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
          - name: SERVER_VERSION
            value: "v2"
          - name: ZOOKEEPER_ENABLED
            value: "false"
      imagePullSecrets:
        - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-server
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: spring-server