apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: spring-server-destinationrule-robin
spec:
  host: spring-server.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2